name: Deploy EC2 (JAR + systemd)
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build (Maven)
        run: mvn -B -DskipTests package

      - name: Encontrar JAR
        id: jar
        run: echo "JAR_PATH=$(ls -1 target/*.jar | head -n1)" >> $GITHUB_OUTPUT

      - name: Upload JAR para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "${{ steps.jar.outputs.JAR_PATH }}"
          target: "/tmp/app.jar"

      - name: Rodar deploy na EC2 (via SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            HEALTH_URL="http://127.0.0.1:8085/actuator/health" KEEP_RELEASES=5 \
              /opt/minha-api/deploy.sh /tmp/app.jar
